
runtime: python37
handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto


# Se necesita crear una carpeta lib y dentro de ella instalar flask y virtualenv con:
# pip install --target lib/ flask
# pip install --target lib/ virtualenv

# Para hacer deploy:
# gcloud app deploy --project pecum-1